import CurlForm from "@/components/curlForm/curlForm";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Curl Requests</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[100vh]  w-full flex items-center justify-center">
        <div className="grid grid-cols-1 gap-x-5 place-items-center place-content-center">
          {[1].map((val, ind) => {
            return <CurlForm key={ind} qnumber={ind + 1} />;
          })}
        </div>
      </main>
    </>
  );
}
